
'''
Variable names in the CIE API
For more info on the terminology and variable names used in the CIE API visit: https://cie-api-v2.climateanalytics.org/api/meta/
'''


Alpha3Codes_Countries = ['ABW', 'AFG', 'AGO', 'AIA', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ASM', 'ATA', 'ATF', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLM', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESH', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GGY', 'GHA', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HKG', 'HMD', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IMN', 'IND', 'IOT', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MSR', 'MUS', 'MWI', 'MYS', 'NAM', 'NCL', 'NER', 'NFK', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PCN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PYF', 'QAT', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SGS', 'SHN', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SPM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TWN', 'TZA', 'UGA', 'UKR', 'URY', 'USA', 'UZB', 'VAT', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLF', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE', 'AFRICA', 'ASIA', 'EUROPE', 'NORTH_AMERICA', 'OCEANIA', 'SOUTH_AMERICA', 'GLOBAL']

VariableNames_Impacts = ["rx5day", "rx1day", "heavy_precipitation_days", "extreme_daily_rainfall", "spei_gamma_12_min", "extreme_drought", "moderate_drought", "severe_drought", "superextreme_drought", "consecutive_dry_days", "drought_intensity", "spei_gamma_12", "wsi", "psAdjust", "tasmaxAdjust", "tasminAdjust", "rldsAdjust", "tasAdjust", "prAdjust", "number_of_wet_days", "hursAdjust", "prsnAdjust", "hussAdjust", "daily_temperature_variability", "total_annual_precipitation", "sfcWindAdjust", "fwils", "fwixd", "dis", "qs", "TXx", "consecutive_tropical_nights", "cooling_degree_days", "wet_bulb_temperature", "HI-danger", "HI-caution", "HI-extreme-danger", "HI-extreme-caution", "labour-productivity-loss", "maize_yield", "rice_yield", "soy_yield", "wheat_yield"]

VariableNames_Scenarios = ["h_cpol", "h_cpol_high_impact", "o_1p5c", "d_strain", "h_ndc", "o_2c", "o_lowdem", "d_delfrag", "cat_current"]

AvailableSeasonalAverages ={"rx5day": ["annual"],
                                "rx1day": ["annual"],
                                "heavy_precipitation_days": ["annual"],
                                "extreme_daily_rainfall": ["annual"],
                                "spei_gamma_12_min": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "extreme_drought": ["annual"],
                                "moderate_drought": ["annual"],
                                "severe_drought": ["annual"],
                                "superextreme_drought": ["annual"],
                                "consecutive_dry_days": ["annual"],
                                "drought_intensity": ["annual"],
                                "spei_gamma_12": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "wsi": ["annual"],
                                "psAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "tasmaxAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "tasminAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "rldsAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "tasAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "prAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "number_of_wet_days": ["annual"],
                                "hursAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "prsnAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "hussAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "daily_temperature_variability": ["annual"],
                                "total_annual_precipitation": ["annual"],
                                "sfcWindAdjust": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "fwils": ["annual"],
                                "fwixd": ["annual"],
                                "dis": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "qs": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "TXx": ["annual"],
                                "consecutive_tropical_nights": ["annual"],
                                "cooling_degree_days": ["annual"],
                                "wet_bulb_temperature": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "HI-danger": ["annual"],
                                "HI-caution": ["annual"],
                                "HI-extreme-danger": ["annual"],
                                "HI-extreme-caution": ["annual"],
                                "labour-productivity-loss": ["annual", "MAM", "JJA", "SON", "DJF"],
                                "maize_yield": ["annual"],
                                "rice_yield": ["annual"],
                                "soy_yield": ["annual"],
                                "wheat_yield": ["annual"]
                                }

AvailableSpatialAggregations = {"rx5day": ["area", "pop", "gdp"],
                                "rx1day": ["area", "pop", "gdp"],
                                "heavy_precipitation_days": ["area", "pop", "gdp"],
                                "extreme_daily_rainfall": ["area", "pop", "gdp"],
                                "spei_gamma_12_min": ["area", "pop", "gdp"],
                                "extreme_drought": ["area", "pop", "gdp", "harvarea"],
                                "moderate_drought": ["area", "pop", "gdp", "harvarea"],
                                "severe_drought": ["area", "pop", "gdp", "harvarea"],
                                "superextreme_drought": ["area", "pop", "gdp", "harvarea"],
                                "consecutive_dry_days": ["area", "pop", "gdp"],
                                "drought_intensity": ["area", "pop", "gdp"],
                                "spei_gamma_12": ["area", "pop", "gdp"],
                                "wsi": ["area", "pop", "gdp"],
                                "psAdjust": ["area", "pop", "gdp"],
                                "tasmaxAdjust": ["area", "pop", "gdp"],
                                "tasminAdjust": ["area", "pop", "gdp"],
                                "rldsAdjust": ["area", "pop", "gdp"],
                                "tasAdjust": ["area", "pop", "gdp"],
                                "prAdjust": ["area", "pop", "gdp"],
                                "number_of_wet_days": ["area", "pop", "gdp"],
                                "hursAdjust": ["area", "pop", "gdp"],
                                "prsnAdjust": ["area", "pop", "gdp"],
                                "hussAdjust": ["area", "pop", "gdp"],
                                "daily_temperature_variability": ["area", "pop", "gdp"],
                                "total_annual_precipitation": ["area", "pop", "gdp"],
                                "sfcWindAdjust": ["area", "pop", "gdp"],
                                "fwils": ["area", "pop", "gdp"],
                                "fwixd": ["area", "pop", "gdp"],
                                "dis": ["area", "pop", "gdp"],
                                "qs": ["area", "pop", "gdp"],
                                "TXx": ["area", "pop", "gdp"],
                                "consecutive_tropical_nights": ["area", "pop", "gdp"],
                                "cooling_degree_days": ["area", "pop", "gdp"],
                                "wet_bulb_temperature": ["area", "pop", "gdp"],
                                "HI-danger": ["area", "pop", "gdp"],
                                "HI-caution": ["area", "pop", "gdp"],
                                "HI-extreme-danger": ["area", "pop", "gdp"],
                                "HI-extreme-caution": ["area", "pop", "gdp"],
                                "labour-productivity-loss": ["area", "pop", "gdp"],
                                "maize_yield": ["area", "maize_yield"],
                                "rice_yield": ["area", "rice_yield"],
                                "soy_yield": ["area", "soybean_yield"],
                                "wheat_yield": ["area", "wheat_yield"]}

Subdivisions = {'ABW': ['ABW'],
                'AFG': ['AF.BD', 'AF.BG', 'AF.BL', 'AF.BK', 'AF.BM', 'AF.DK', 'AF.FH',
                        'AF.FB', 'AF.GZ', 'AF.GR', 'AF.HM', 'AF.HR', 'AF.JW', 'AF.KB',
                        'AF.KD', 'AF.KP', 'AF.KT', 'AF.KR', 'AF.KZ', 'AF.LA', 'AF.LW',
                        'AF.NG', 'AF.NM', 'AF.NR', 'AF.PK', 'AF.PT', 'AF.PJ', 'AF.PV',
                        'AF.SM', 'AF.SP', 'AF.TK', 'AF.OZ', 'AF.VR', 'AF.ZB', 'AFG'],
                'AGO': ['AO.BO', 'AO.BG', 'AO.BI', 'AO.CB', 'AO.CC', 'AO.CN', 'AO.CS',
                        'AO.CU', 'AO.HL', 'AO.HM', 'AO.LU', 'AO.LN', 'AO.LS', 'AO.ML',
                        'AO.MX', 'AO.NA', 'AO.UI', 'AO.ZA', 'AGO'], 'AIA': ['AIA'],
                'ALB': ['AL.BE', 'AL.DB', 'AL.DU', 'AL.EB', 'AL.FI', 'AL.GK', 'AL.KE',
                        'AL.KK', 'AL.LZ', 'AL.SD', 'AL.TI', 'AL.VR', 'ALB'],
                'AND': ['AD.AN', 'AD.CA', 'AD.EN', 'AD.EE', 'AD.MA', 'AD.OR', 'AD.JL',
                        'AND'],
                'ARE': ['AE.AZ', 'AE.AJ', 'AE.DU', 'AE.FU', 'AE.RK', 'AE.SH', 'AE.UQ',
                        'ARE'],
                'ARG': ['AR.BA', 'AR.CB', 'AR.CT', 'AR.CC', 'AR.CH', 'AR.DF', 'AR.CN',
                        'AR.ER', 'AR.FM', 'AR.JY', 'AR.LP', 'AR.LR', 'AR.MZ', 'AR.MN',
                        'AR.NQ', 'AR.RN', 'AR.SA', 'AR.SJ', 'AR.SL', 'AR.SC', 'AR.SF',
                        'AR.SE', 'AR.TF', 'AR.TM', 'ARG'],
                'ARM': ['AM.AG', 'AM.AR', 'AM.AV', 'AM.ER', 'AM.GR', 'AM.KT', 'AM.LO',
                        'AM.SH', 'AM.SU', 'AM.TV', 'AM.VD', 'ARM'],
                'ASM': ['AS.ET', 'AS.MA', 'AS.UU', 'AS.WT', 'ASM'], 'ATA': ['ATA'],
                'ATF': ['TF.CR', 'TF.AS', 'TF.KG', 'ATF'],
                'ATG': ['AG.BB', 'AG.RD', 'AG.GE', 'AG.JO', 'AG.MA', 'AG.PA', 'AG.PE',
                        'AG.PH', 'ATG'],
                'AUS': ['AU.AS', 'AU.CT', 'AU.CR', 'AU.JB', 'AU.NS', 'AU.NT', 'AU.QL',
                        'AU.SA', 'AU.TS', 'AU.VI', 'AU.WA', 'AUS'],
                'AUT': ['AT.BU', 'AT.KA', 'AT.NO', 'AT.OO', 'AT.SZ', 'AT.ST', 'AT.TR',
                        'AT.VO', 'AT.WI', 'AUT'], 'AZE': ['AZE'],
                'BDI': ['BI.BB', 'BI.BM', 'BI.BU', 'BI.BR', 'BI.CA', 'BI.CI', 'BI.GI',
                        'BI.KR', 'BI.KY', 'BI.KI', 'BI.MA', 'BI.MV', 'BI.MY', 'BI.MW',
                        'BI.NG', 'BI.RT', 'BI.RY', 'BDI'], 'BEL': ['BEL'],
                'BEN': ['BJ.AL', 'BJ.AK', 'BJ.AQ', 'BJ.BO', 'BJ.CL', 'BJ.DO', 'BJ.CF',
                        'BJ.LI', 'BJ.MO', 'BJ.OU', 'BJ.PL', 'BJ.ZO', 'BEN'],
                'BFA': ['BF.BO', 'BF.CD', 'BF.CT', 'BF.CE', 'BF.CN', 'BF.CO', 'BF.CS',
                        'BF.ES', 'BF.HB', 'BF.NO', 'BF.PC', 'BF.SA', 'BF.SO', 'BFA'],
                'BGD': ['BD.BA', 'BD.CG', 'BD.DA', 'BD.KH', 'BD.RS', 'BD.RP', 'BD.SY',
                        'BGD'],
                'BGR': ['BG.BL', 'BG.BR', 'BG.DO', 'BG.GB', 'BG.SG', 'BG.KK', 'BG.KZ',
                        'BG.KY', 'BG.LV', 'BG.MT', 'BG.PZ', 'BG.PN', 'BG.PV', 'BG.PD',
                        'BG.RG', 'BG.RS', 'BG.SH', 'BG.SI', 'BG.SL', 'BG.SM', 'BG.SF',
                        'BG.SZ', 'BG.TU', 'BG.VN', 'BG.VT', 'BG.VD', 'BG.VR', 'BG.YA',
                        'BGR'],
                'BHR': ['BH.CA', 'BH.CE', 'BH.MU', 'BH.NO', 'BH.SO', 'BHR'],
                'BHS': ['BS.AK', 'BS.BR', 'BS.BI', 'BS.BP', 'BS.CI', 'BS.CB', 'BS.CN',
                        'BS.CE', 'BS.FP', 'BS.CK', 'BS.EB', 'BS.EM', 'BS.GC', 'BS.HB',
                        'BS.HT', 'BS.IN', 'BS.LI', 'BS.MC', 'BS.MG', 'BS.MI', 'BS.NW',
                        'BS.NB', 'BS.NN', 'BS.NE', 'BS.RI', 'BS.RC', 'BS.SS', 'BS.SB',
                        'BS.SN', 'BS.SE', 'BS.SW', 'BS.WB', 'BHS'],
                'BIH': ['BA.BR', 'BA.BF', 'BA.SR', 'BIH'], 'BLM': ['BLM'],
                'BLR': ['BY.BR', 'BY.HO', 'BY.HR', 'BY.MA', 'BY.MI', 'BY.VI', 'BLR'],
                'BLZ': ['BZ.BZ', 'BZ.CY', 'BZ.CZ', 'BZ.OW', 'BZ.SC', 'BZ.TO', 'BLZ'],
                'BMU': ['BM.DE', 'BM.HC', 'BM.HA', 'BM.PA', 'BM.PE', 'BM.SC', 'BM.SG',
                        'BM.SA', 'BM.SM', 'BM.SO', 'BM.WA', 'BMU'],
                'BOL': ['BO.CQ', 'BO.CB', 'BO.EB', 'BO.LP', 'BO.OR', 'BO.PA', 'BO.PO',
                        'BO.SC', 'BO.TR', 'BOL'],
                'BRA': ['BR.AC', 'BR.AL', 'BR.AP', 'BR.AM', 'BR.BA', 'BR.CE', 'BR.DF',
                        'BR.ES', 'BR.GO', 'BR.MA', 'BR.MS', 'BR.MT', 'BR.MG', 'BR.PA',
                        'BR.PB', 'BR.PR', 'BR.PE', 'BR.PI', 'BR.RJ', 'BR.RN', 'BR.RS',
                        'BR.RO', 'BR.RR', 'BR.SP', 'BR.SC', 'BR.SE', 'BR.TO', 'BRA'],
                'BRB': ['BB.CC', 'BB.AN', 'BB.GE', 'BB.JM', 'BB.JN', 'BB.JS', 'BB.LU',
                        'BB.MI', 'BB.PE', 'BB.PH', 'BB.TH', 'BRB'],
                'BRN': ['BN.BE', 'BN.BM', 'BN.TE', 'BN.TU', 'BRN'],
                'BTN': ['BT.BU', 'BT.CK', 'BT.DA', 'BT.GA', 'BT.HA', 'BT.LH', 'BT.MO',
                        'BT.PR', 'BT.PM', 'BT.PN', 'BT.SJ', 'BT.SM', 'BT.GE', 'BT.TM',
                        'BT.TA', 'BT.TO', 'BT.CR', 'BT.WP', 'BT.TY', 'BT.SG', 'BTN'],
                'BWA': ['BW.CE', 'BW.CH', 'BW.FR', 'BW.GB', 'BW.GH', 'BW.JW', 'BW.KG',
                        'BW.KL', 'BW.KW', 'BW.LB', 'BW.NE', 'BW.NC', 'BW.SP', 'BW.SR',
                        'BW.SO', 'BW.ST', 'BWA'],
                'CAF': ['CF.BB', 'CF.BG', 'CF.BK', 'CF.HM', 'CF.HK', 'CF.KG', 'CF.LB',
                        'CF.HS', 'CF.MB', 'CF.KB', 'CF.NM', 'CF.MP', 'CF.UK', 'CF.OP',
                        'CF.AC', 'CF.SE', 'CF.VK', 'CAF'],
                'CAN': ['CAN', 'CAN.1_1', 'CAN.2_1', 'CAN.3_1', 'CAN.4_1', 'CAN.5_1',
                        'CAN.6_1', 'CAN.7_1', 'CAN.8_1', 'CAN.9_1', 'CAN.10_1',
                        'CAN.11_1', 'CAN.12_1', 'CAN.13_1'],
                'CHE': ['CH.AG', 'CH.AR', 'CH.AI', 'CH.BL', 'CH.BS', 'CH.BE', 'CH.FR',
                        'CH.GE', 'CH.GL', 'CH.GR', 'CH.JU', 'CH.LU', 'CH.NE', 'CH.NW',
                        'CH.OW', 'CH.SG', 'CH.SH', 'CH.SZ', 'CH.SO', 'CH.TG', 'CH.TI',
                        'CH.UR', 'CH.VS', 'CH.VD', 'CH.ZH', 'CH.ZG', 'CHE'],
                'CHL': ['CL.AI', 'CL.AN', 'CL.AR', 'CL.AP', 'CL.AT', 'CL.BI', 'CL.CO',
                        'CL.LI', 'CL.LL', 'CL.LR', 'CL.MA', 'CL.ML', 'CL.RM', 'CL.TA',
                        'CL.VS', 'CHL'],
                'CHN': ['CN.AH', 'CN.BJ', 'CN.CQ', 'CN.FJ', 'CN.GS', 'CN.GD', 'CN.GX',
                        'CN.GZ', 'CN.HA', 'CN.HB', 'CN.HL', 'CN.HE', 'CN.HU', 'CN.HN',
                        'CN.JS', 'CN.JX', 'CN.JL', 'CN.LN', 'CN.NM', 'CN.NX', 'CN.QH',
                        'CN.SA', 'CN.SD', 'CN.SH', 'CN.SX', 'CN.SC', 'CN.TJ', 'CN.XJ',
                        'CN.XZ', 'CN.YN', 'CN.ZJ', 'CHN'],
                'CIV': ['CI.AB', 'CI.BS', 'CI.CM', 'CI.DE', 'CI.GD', 'CI.LA', 'CI.LN',
                        'CI.MN', 'CI.SM', 'CI.SV', 'CI.VB', 'CI.WB', 'CI.YM', 'CI.ZA',
                        'CIV'],
                'CMR': ['CM.AD', 'CM.CE', 'CM.ES', 'CM.EN', 'CM.LT', 'CM.NW', 'CM.NO',
                        'CM.OU', 'CM.SW', 'CM.SU', 'CMR'],
                'COD': ['CD.EQ', 'CD.BN', 'CD.BC', 'CD.KC', 'CD.KR', 'CD.KT', 'CD.KN',
                        'CD.KV', 'CD.HC', 'COD'],
                'COG': ['CG.BO', 'CG.BR', 'CG.CO', 'CG.CU', 'CG.KO', 'CG.LE', 'CG.LI',
                        'CG.NI', 'CG.PL', 'CG.PN', 'CG.PO', 'CG.SA', 'COG'],
                'COK': ['COK'],
                'COL': ['CO.AM', 'CO.AN', 'CO.AR', 'CO.AT', 'CO.BL', 'CO.BY', 'CO.CO',
                        'CO.CL', 'CO.CQ', 'CO.CS', 'CO.CA', 'CO.CE', 'CO.CH', 'CO.CU',
                        'CO.GN', 'CO.GV', 'CO.HU', 'CO.LG', 'CO.MA', 'CO.ME', 'CO.NA',
                        'CO.NS', 'CO.PU', 'CO.QD', 'CO.RI', 'CO.SA', 'CO.ST', 'CO.SU',
                        'CO.TO', 'CO.VC', 'CO.VP', 'CO.VD', 'COL'],
                'COM': ['KM.MO', 'KM.GC', 'KM.AN', 'COM'],
                'CPV': ['CV.BV', 'CV.BR', 'CV.MA', 'CV.MO', 'CV.PA', 'CV.PN', 'CV.PC',
                        'CV.RB', 'CV.RS', 'CV.RG', 'CV.SD', 'CV.FP', 'CV.LO', 'CV.SM',
                        'CV.SS', 'CV.SV', 'CV.SL', 'CV.CT', 'CV.CZ', 'CV.TS', 'CV.TF',
                        'CPV'],
                'CRI': ['CR.AL', 'CR.CA', 'CR.GU', 'CR.HE', 'CR.LI', 'CR.PU', 'CR.SJ',
                        'CRI'],
                'CUB': ['CU.CM', 'CU.CA', 'CU.CF', 'CU.CH', 'CU.GR', 'CU.GU', 'CU.HO',
                        'CU.IJ', 'CU.LH', 'CU.LT', 'CU.MA', 'CU.MQ', 'CU.PR', 'CU.SS',
                        'CU.SC', 'CU.VC', 'CUB'], 'CUW': ['CUW'],
                'CYM': ['KY.BT', 'KY.CB', 'KY.EE', 'KY.GT', 'KY.SO', 'KY.NS', 'KY.WB',
                        'CYM'],
                'CYP': ['CY.FA', 'CY.LA', 'CY.LI', 'CY.NI', 'CY.PA', 'CYP'],
                'CZE': ['CZ.UK', 'CZ.CK', 'CZ.BK', 'CZ.KK', 'CZ.HK', 'CZ.JK', 'CZ.LK',
                        'CZ.VK', 'CZ.OK', 'CZ.EK', 'CZ.PK', 'CZ.SK', 'CZ.ZK', 'CZE'],
                'DEU': ['DE.BW', 'DE.BY', 'DE.BE', 'DE.BR', 'DE.HB', 'DE.HH', 'DE.HE',
                        'DE.MV', 'DE.NI', 'DE.NW', 'DE.RP', 'DE.SL', 'DE.ST', 'DE.SN',
                        'DE.SH', 'DE.TH', 'DEU'],
                'DJI': ['DJ.AS', 'DJ.DK', 'DJ.DB', 'DJ.OB', 'DJ.TA', 'DJI'],
                'DMA': ['DM.AN', 'DM.DA', 'DM.GO', 'DM.JN', 'DM.JH', 'DM.LU', 'DM.MA',
                        'DM.PK', 'DM.PL', 'DM.PR', 'DMA'],
                'DNK': ['DK.HS', 'DK.MJ', 'DK.ND', 'DK.SL', 'DK.SD', 'DNK'],
                'DOM': ['DO.AZ', 'DO.BR', 'DO.BH', 'DO.DA', 'DO.NC', 'DO.DU', 'DO.SE',
                        'DO.ES', 'DO.HM', 'DO.IN', 'DO.AL', 'DO.EP', 'DO.RO', 'DO.VE',
                        'DO.MT', 'DO.MN', 'DO.MC', 'DO.MP', 'DO.PN', 'DO.PV', 'DO.PP',
                        'DO.SZ', 'DO.SC', 'DO.SM', 'DO.CR', 'DO.JO', 'DO.JU', 'DO.PM',
                        'DO.SR', 'DO.ST', 'DO.SD', 'DO.VA', 'DOM'],
                'DZA': ['DZ.AD', 'DZ.AT', 'DZ.AR', 'DZ.AL', 'DZ.AN', 'DZ.BC', 'DZ.BJ',
                        'DZ.BT', 'DZ.BS', 'DZ.BL', 'DZ.BB', 'DZ.BU', 'DZ.BM', 'DZ.CH',
                        'DZ.CO', 'DZ.DJ', 'DZ.EB', 'DZ.EO', 'DZ.ET', 'DZ.GR', 'DZ.GL',
                        'DZ.IL', 'DZ.JJ', 'DZ.KH', 'DZ.LG', 'DZ.MS', 'DZ.MD', 'DZ.MC',
                        'DZ.ML', 'DZ.MG', 'DZ.NA', 'DZ.OR', 'DZ.OG', 'DZ.OB', 'DZ.RE',
                        'DZ.SF', 'DZ.SD', 'DZ.SB', 'DZ.SK', 'DZ.SA', 'DZ.TB', 'DZ.TM',
                        'DZ.TR', 'DZ.TN', 'DZ.TP', 'DZ.TS', 'DZ.TO', 'DZ.TL', 'DZA'],
                'ECU': ['EC.AZ', 'EC.BO', 'EC.CN', 'EC.CR', 'EC.CB', 'EC.CT', 'EC.EO',
                        'EC.ES', 'EC.GA', 'EC.GU', 'EC.IM', 'EC.LJ', 'EC.LR', 'EC.MN',
                        'EC.MS', 'EC.NA', 'EC.OR', 'EC.PA', 'EC.PI', 'EC.SE', 'EC.SD',
                        'EC.SU', 'EC.TU', 'EC.ZC', 'ECU'],
                'EGY': ['EG.DQ', 'EG.BA', 'EG.BH', 'EG.FY', 'EG.GH', 'EG.IK', 'EG.IS',
                        'EG.JZ', 'EG.MF', 'EG.MN', 'EG.QH', 'EG.QL', 'EG.UQ', 'EG.WJ',
                        'EG.SW', 'EG.SQ', 'EG.AN', 'EG.AT', 'EG.BN', 'EG.BS', 'EG.DT',
                        'EG.JS', 'EG.KS', 'EG.MT', 'EG.QN', 'EG.SS', 'EG.SJ', 'EGY'],
                'ERI': ['ER.AN', 'ER.DK', 'ER.DU', 'ER.GB', 'ER.MA', 'ER.SK', 'ERI'],
                'ESH': ['ESH', 'ESH.1_1', 'ESH.2_1', 'ESH.3_1', 'ESH.4_1'],
                'ESP': ['ES.AN', 'ES.AR', 'ES.CB', 'ES.CM', 'ES.CL', 'ES.CT', 'ES.ML',
                        'ES.MD', 'ES.NA', 'ES.VC', 'ES.EX', 'ES.GA', 'ES.PM', 'ES.CN',
                        'ES.LO', 'ES.PV', 'ES.AS', 'ES.MU', 'ESP'],
                'EST': ['EE.HA', 'EE.HI', 'EE.IV', 'EE.JR', 'EE.JN', 'EE.LN', 'EE.LV',
                        'EE.PR', 'EE.PL', 'EE.RA', 'EE.SA', 'EE.TA', 'EE.VG', 'EE.VD',
                        'EE.VR', 'EST'],
                'ETH': ['ET.AA', 'ET.AF', 'ET.AM', 'ET.BE', 'ET.DD', 'ET.GA', 'ET.HA',
                        'ET.OR', 'ET.SO', 'ET.SN', 'ET.TI', 'ETH'],
                'FIN': ['FI.IS', 'FI.LP', 'FI.OU', 'FI.ES', 'FI.LS', 'FIN'],
                'FJI': ['FJ.CE', 'FJ.EA', 'FJ.NO', 'FJ.RO', 'FJ.W', 'FJI'],
                'FLK': ['FLK'],
                'FRA': ['FR.AR', 'FR.BF', 'FR.BT', 'FR.CN', 'FR.CE', 'FR.AO', 'FR.NC',
                        'FR.IF', 'FR.ND', 'FR.AC', 'FR.LP', 'FR.PL', 'FR.PR', 'FRA'],
                'FRO': ['FO.OS', 'FO.NO', 'FO.SA', 'FO.ST', 'FO.SN|FO.SS', 'FO.VG',
                        'FRO'], 'FSM': ['FM.CH', 'FM.KO', 'FM.PO', 'FM.YA', 'FSM'],
                'GAB': ['GA.ES', 'GA.HO', 'GA.MO', 'GA.NG', 'GA.NY', 'GA.OI', 'GA.OL',
                        'GA.OM', 'GA.WN', 'GAB'], 'GBR': ['GBR'],
                'GEO': ['GE.AB', 'GE.AJ', 'GE.GU', 'GE.IM', 'GE.KA', 'GE.KK', 'GE.MM',
                        'GE.RK', 'GE.SZ', 'GE.SJ', 'GE.SD', 'GE.TB', 'GEO'],
                'GGY': ['GG.AL', 'GG.BQ', 'GG.CA', 'GG.FO', 'GG.HM', 'GG.JT', 'GG.AN',
                        'GG.MA', 'GG.PP', 'GG.SB', 'GG.SM', 'GG.SV', 'GG.SK', 'GG.TV',
                        'GG.VA', 'GGY'],
                'GHA': ['GH.AH', 'GH.BA', 'GH.CP', 'GH.EP', 'GH.AA', 'GH.NP', 'GH.UE',
                        'GH.UW', 'GH.TV', 'GH.WP', 'GHA'], 'GIN': ['GIN'],
                'GMB': ['GM.BJ', 'GM.LR', 'GM.MC', 'GM.NB', 'GM.UR', 'GM.WE', 'GMB'],
                'GNB': ['GW.BA', 'GW.BM', 'GW.BS', 'GW.BL', 'GW.CA', 'GW.GA', 'GW.OI',
                        'GW.QU', 'GW.TO', 'GNB'],
                'GNQ': ['GQ.AN', 'GQ.BN', 'GQ.BS', 'GQ.CS', 'GQ.KN', 'GQ.LI', 'GQ.WN',
                        'GNQ'],
                'GRC': ['GR.AI', 'GR.MA', 'GR.AT', 'GR.CR', 'GR.EM', 'GR.MH', 'GR.PW',
                        'GR.TC', 'GRC'],
                'GRD': ['GD.CA', 'GD.AN', 'GD.DA', 'GD.GE', 'GD.JO', 'GD.MA', 'GD.PA',
                        'GRD'],
                'GRL': ['GL.KU', 'GL.UO', 'GL.QS', 'GL.QT', 'GL.SE', 'GRL'],
                'GTM': ['GT.AV', 'GT.BV', 'GT.CM', 'GT.CQ', 'GT.PR', 'GT.ES', 'GT.GU',
                        'GT.HU', 'GT.IZ', 'GT.JA', 'GT.JU', 'GT.PE', 'GT.QZ', 'GT.QC',
                        'GT.RE', 'GT.SA', 'GT.SM', 'GT.SR', 'GT.SO', 'GT.SU', 'GT.TO',
                        'GT.ZA', 'GTM'],
                'GUM': ['GU.AH', 'GU.AT', 'GU.AS', 'GU.BA', 'GU.CP', 'GU.DD', 'GU.AN',
                        'GU.IN', 'GU.MA', 'GU.ME', 'GU.MT', 'GU.PI', 'GU.SR', 'GU.SJ',
                        'GU.TF', 'GU.TM', 'GU.UM', 'GU.YG', 'GU.YN', 'GUM'],
                'GUY': ['GY.BA', 'GY.CU', 'GY.DE', 'GY.EB', 'GY.ES', 'GY.MA', 'GY.PM',
                        'GY.PT', 'GY.UD', 'GY.UT', 'GUY'],
                'HKG': ['HK.CW', 'HK.EA', 'HK.IS', 'HK.KC', 'HK.KI', 'HK.KU', 'HK.NO',
                        'HK.SK', 'HK.ST', 'HK.SS', 'HK.SO', 'HK.TP', 'HK.TW', 'HK.TM',
                        'HK.WC', 'HK.WT', 'HK.YT', 'HK.YL', 'HKG'], 'HMD': ['HMD'],
                'HND': ['HN.AT', 'HN.CH', 'HN.CL', 'HN.CM', 'HN.CP', 'HN.CR', 'HN.EP',
                        'HN.FM', 'HN.GD', 'HN.IN', 'HN.IB', 'HN.LP', 'HN.LE', 'HN.OC',
                        'HN.OL', 'HN.VA', 'HN.YO', 'HND'],
                'HRV': ['HR.SB', 'HR.BB', 'HR.SP', 'HR.DN', 'HR.GZ', 'HR.IS', 'HR.KA',
                        'HR.KK', 'HR.KZ', 'HR.LS', 'HR.ME', 'HR.OB', 'HR.PS', 'HR.PG',
                        'HR.SM', 'HR.SD', 'HR.VA', 'HR.VP', 'HR.VS', 'HR.ZD', 'HR.ZG',
                        'HRV'],
                'HTI': ['HT.CE', 'HT.GR', 'HT.AR', 'HT.NI', 'HT.NE', 'HT.NO', 'HT.ND',
                        'HT.OU', 'HT.SE', 'HT.SD', 'HTI'],
                'HUN': ['HU.BK', 'HU.BE', 'HU.BA', 'HU.BZ', 'HU.BU', 'HU.CS', 'HU.FE',
                        'HU.GS', 'HU.HB', 'HU.HE', 'HU.JN', 'HU.KE', 'HU.NO', 'HU.PE',
                        'HU.SO', 'HU.SZ', 'HU.TO', 'HU.VA', 'HU.VE', 'HU.ZA', 'HUN'],
                'IDN': ['IDN.1_1', 'IDN.2_1', 'IDN.3_1', 'IDN.4_1', 'IDN.5_1',
                        'IDN.6_1', 'IDN.7_1', 'IDN.8_1', 'IDN.9_1', 'IDN.10_1',
                        'IDN.11_1', 'IDN.12_1', 'IDN.13_1', 'IDN.14_1', 'IDN.15_1',
                        'IDN.16_1', 'IDN.17_1', 'IDN.19_1', 'IDN.18_1', 'IDN.20_1',
                        'IDN.21_1', 'IDN.23_1', 'IDN.22_1', 'IDN.24_1', 'IDN.25_1',
                        'IDN.26_1', 'IDN.27_1', 'IDN.28_1', 'IDN.29_1', 'IDN.30_1',
                        'IDN.31_1', 'IDN.32_1', 'IDN.33_1', 'IDN'],
                'IMN': ['IM.AY', 'IM.GR', 'IM.GB', 'IM.MC', 'IM.MD', 'IM.RU', 'IMN'],
                'IND': ['IN.AN', 'IN.AP', 'IN.AR', 'IN.AS', 'IN.BR', 'IN.CH', 'IN.CT',
                        'IN.DN', 'IN.DD', 'IN.GA', 'IN.GJ', 'IN.HR', 'IN.HP', 'IN.JK',
                        'IN.JH', 'IN.KA', 'IN.KL', 'IN.LD', 'IN.MP', 'IN.MH', 'IN.MN',
                        'IN.ML', 'IN.MZ', 'IN.NL', 'IN.DL', 'IN.OR', 'IN.PY', 'IN.PB',
                        'IN.RJ', 'IN.SK', 'IN.TN', 'IN.TG', 'IN.TR', 'IN.UP', 'IN.UT',
                        'IN.WB', 'IND'], 'IOT': ['IOT'],
                'IRL': ['IE.CW', 'IE.CN', 'IE.CE', 'IE.CK', 'IE.DL', 'IE.DN', 'IE.GY',
                        'IE.KY', 'IE.KE', 'IE.KK', 'IE.LS', 'IE.LM', 'IE.LK', 'IE.LD',
                        'IE.LH', 'IE.MO', 'IE.MH', 'IE.MN', 'IE.OY', 'IE.RN', 'IE.SO',
                        'IE.TY', 'IE.WD', 'IE.WH', 'IE.WX', 'IE.WW', 'IRL'],
                'IRN': ['IR.AL', 'IR.AR', 'IR.BS', 'IR.CM', 'IR.EA', 'IR.ES', 'IR.FA',
                        'IR.GI', 'IR.GO', 'IR.HD', 'IR.HG', 'IR.IL', 'IR.KE', 'IR.BK',
                        'IR.KZ', 'IR.KB', 'IR.KD', 'IR.LO', 'IR.MK', 'IR.MN', 'IR.KS',
                        'IR.QZ', 'IR.QM', 'IR.KV', 'IR.SM', 'IR.SB', 'IR.KJ', 'IR.TH',
                        'IR.WA', 'IR.YA', 'IR.ZA', 'IRN'],
                'IRQ': ['IQ.AN', 'IQ.BA', 'IQ.MU', 'IQ.QA', 'IQ.NA', 'IQ.AR', 'IQ.SU',
                        'IQ.TS', 'IQ.BB', 'IQ.BG', 'IQ.DQ', 'IQ.DA', 'IQ.DI', 'IQ.KA',
                        'IQ.MA', 'IQ.NI', 'IQ.SD', 'IQ.WA', 'IRQ'],
                'ISL': ['IS.AL', 'IS.NE', 'IS.HO', 'IS.NV', 'IS.SL', 'IS.SU', 'IS.VF',
                        'IS.VL', 'ISL'],
                'ISR': ['IL.HD', 'IL.HA', 'IL.HM', 'IL.HZ', 'IL.JM', 'IL.TA', 'ISR'],
                'ITA': ['ITA'],
                'JAM': ['JM.CL', 'JM.HA', 'JM.KI', 'JM.MA', 'JM.PO', 'JM.SD', 'JM.SN',
                        'JM.SC', 'JM.SE', 'JM.SJ', 'JM.SM', 'JM.ST', 'JM.TR', 'JM.WE',
                        'JAM'],
                'JEY': ['JE.GR', 'JE.BR', 'GR.CL', 'JE.HE', 'JE.JO', 'JE.LA', 'JE.MT',
                        'JE.MY', 'JE.OU', 'JE.PE', 'JE.SA', 'JE.TR', 'JEY'],
                'JOR': ['JO.AJ', 'JO.AM', 'JO.AQ', 'JO.BA', 'JO.IR', 'JO.JA', 'JO.KA',
                        'JO.MN', 'JO.MD', 'JO.MA', 'JO.AT', 'JO.AZ', 'JOR'],
                'JPN': ['JP.AI', 'JP.AK', 'JP.AO', 'JP.CH', 'JP.EH', 'JP.FI', 'JP.FO',
                        'JP.FS', 'JP.GF', 'JP.GM', 'JP.HS', 'JP.HK', 'JP.HG', 'JP.IB',
                        'JP.IS', 'JP.IW', 'JP.KG', 'JP.KS', 'JP.KN', 'JP.KC', 'JP.KM',
                        'JP.KY', 'JP.ME', 'JP.MG', 'JP.MZ', 'JP.NN', 'JP.NS', 'JP.NR',
                        'JP.NI', 'JP.OT', 'JP.OY', 'JP.ON', 'JP.OS', 'JP.SG', 'JP.ST',
                        'JP.SH', 'JP.SM', 'JP.SZ', 'JP.TC', 'JP.TS', 'JP.TK', 'JP.TT',
                        'JP.TY', 'JP.WK', 'JP.YT', 'JP.YC', 'JP.YN', 'JPN'],
                'KAZ': ['KZ.AA', 'KZ.AM', 'KZ.AT', 'KZ.AR', 'KZ.EK', 'KZ.MG', 'KZ.NK',
                        'KZ.PA', 'KZ.QG', 'KZ.QS', 'KZ.QO', 'KZ.SK', 'KZ.WK', 'KZ.ZM',
                        'KAZ'],
                'KEN': ['KE.BA', 'KE.BO', 'KE.BN', 'KE.BS', 'KE.EM', 'KE.EB', 'KE.GA',
                        'KE.HB', 'KE.IS', 'KE.KJ', 'KE.KK', 'KE.KR', 'KE.KB', 'KE.KF',
                        'KE.KY', 'KE.KI', 'KE.KU', 'KE.KT', 'KE.KW', 'KE.LK', 'KE.LM',
                        'KE.MC', 'KE.MK', 'KE.MD', 'KE.MB', 'KE.ME', 'KE.MG', 'KE.MM',
                        'KE.MU', 'KE.NB', 'KE.NK', 'KE.ND', 'KE.NR', 'KE.NM', 'KE.NN',
                        'KE.NI', 'KE.SA', 'KE.SI', 'KE.TT', 'KE.TR', 'KE.NT', 'KE.TN',
                        'KE.TU', 'KE.UG', 'KE.VI', 'KE.WJ', 'KE.WP', 'KEN'],
                'KGZ': ['KG.BA', 'KG.GB', 'KG.CU', 'KG.DA', 'KG.NA', 'KG.OS', 'KG.TL',
                        'KG.YK', 'KGZ'],
                'KHM': ['KH.OM', 'KH.BA', 'KH.KP', 'KH.KM', 'KH.KG', 'KH.KS', 'KH.KT',
                        'KH.KN', 'KH.KK', 'KH', 'KH.KH', 'KH.PL', 'KH.KA', 'KH.MK',
                        'KH.OC', 'KH.PP', 'KH.PO', 'KH.PH', 'KH.PY', 'KH.RO', 'KH.SI',
                        'KH.ST', 'KH.SR', 'KH.TA', 'KH.TB', 'KHM'], 'KIR': ['KIR'],
                'KNA': ['KN.CC', 'KN.AS', 'KN.GB', 'KN.GG', 'KN.JW', 'KN.JC', 'KN.JF',
                        'KN.MC', 'KN.PP', 'KN.PL', 'KN.PB', 'KN.TL', 'KN.TM', 'KN.TP',
                        'KNA'],
                'KOR': ['KR.PU', 'KR.GB', 'KR.GN', 'KR.TG', 'KR.TJ', 'KR.KW', 'KR.KJ',
                        'KR.KG', 'KR.KB', 'KR.KN', 'KR.IN', 'KR.CJ', 'KR.CB', 'KR.CN',
                        'KR.SJ', 'KR.SO', 'KR.UL', 'KOR'],
                'KWT': ['KW.AH', 'KW.FA', 'KW.JA', 'KW.KU', 'KW.HW', 'KW.MU', 'KWT'],
                'LAO': ['LA.AT', 'LA.BK', 'LA.BL', 'LA.CH', 'LA.HO', 'LA.KH', 'LA.LM',
                        'LA.LP', 'LA.OU', 'LA.PH', 'LA.SL', 'LA.SV', 'LA.VT', 'LA.VI',
                        'LA.XE', 'LA.XA', 'LA.XS', 'LA.XI', 'LAO'], 'LBN': ['LBN'],
                'LBR': ['LR.BM', 'LR.BG', 'LR.GP', 'LR.CM', 'LR.GB', 'LR.GD', 'LR.GK',
                        'LR.LF', 'LR.MG', 'LR.MY', 'LR.MO', 'LR.NI', 'LR.RI', 'LR.RG',
                        'LR.SI', 'LBR'],
                'LBY': ['LY.BN', 'LY.JK', 'LY.JG', 'LY.JR', 'LY.JF', 'LY.KU', 'LY.MA',
                        'LY.MR', 'LY.AW', 'LY.NK', 'LY.ZW', 'LY.BG', 'LY.DA', 'LY.GH',
                        'LY. MS', 'LY.MU', 'LY.NT', 'LY.SA', 'LY.ST', 'LY.TR', 'LY.WH',
                        'LY.WS', 'LBY'],
                'LCA': ['LC.AR', 'LC.CN', 'LC.CS', 'LC.CH', 'LC.DE', 'LC.GI', 'LC.LB',
                        'LC.MI', 'LC.CO', 'LC.VF', 'LCA'],
                'LIE': ['LI.BA', 'LI.ES', 'LI.GA', 'LI.MA', 'LI.PL', 'LI.RU', 'LI.SN',
                        'LI.SB', 'LI.TB', 'LI.TN', 'LI.VA', 'LIE'],
                'LKA': ['LK.AP', 'LK.AD', 'LK.BD', 'LK.BC', 'LK.CO', 'LK.GL', 'LK.GQ',
                        'LK.HB', 'LK.JA', 'LK.KT', 'LK.KY', 'LK.KE', 'LK.KL', 'LK.KG',
                        'LK.MB', 'LK.MT', 'LK.MH', 'LK.MJ', 'LK.MP', 'LK.NW', 'LK.PR',
                        'LK.PX', 'LK.RN', 'LK.TC', 'LK.VA', 'LKA'],
                'LSO': ['LS.BE', 'LS.BB', 'LS.LE', 'LS.MF', 'LS.MS', 'LS.MH', 'LS.MK',
                        'LS.QN', 'LS.QT', 'LS.TT', 'LSO'],
                'LTU': ['LT.SH', 'LT.AS', 'LT.KS', 'LT.KP', 'LT.MA', 'LT.PA', 'LT.TG',
                        'LT.TL', 'LT.UN', 'LT.VI', 'LTU'],
                'LUX': ['LU.DI', 'LU.GR', 'LU.LU', 'LUX'],
                'LVA': ['K', 'L', 'R', 'V', 'Z', 'LVA'],
                'MAC': ['MO.IL', 'MO.MA', 'MAC'], 'MAF': ['MAF'],
                'MAR': ['MA.CO', 'MA.DA', 'MA.FB', 'MA.GB', 'MA.GC', 'MA.GE', 'MA.LB',
                        'MA.MK', 'MA.MT', 'MA.OR', 'MA.RZ', 'MA.SM', 'MA.TD', 'MA.TO',
                        'MA.TH', 'MAR'], 'MCO': ['MCO'],
                'MDA': ['MD.AN', 'MD.SD', 'MD.SV', 'MD.BT', 'MD.BA', 'MD.BD', 'MD.BR',
                        'MD.CH', 'MD.CA', 'MD.CN', 'MD.CU', 'MD.CV', 'MD.CS', 'MD.CR',
                        'MD.DO', 'MD.DR', 'MD.DB', 'MD.ED', 'MD.FA', 'MD.FL', 'MD.GA',
                        'MD.GL', 'MD.HI', 'MD.IA', 'MD.LE', 'MD.NI', 'MD.OC', 'MD.OH',
                        'MD.RS', 'MD.RZ', 'MD.SI', 'MD.SO', 'MD.ST', 'MD.TA', 'MD.TE',
                        'MD.DU', 'MD.UG', 'MDA'],
                'MDG': ['MG.AV', 'MG.AS', 'MG.FI', 'MG.MA', 'MG.TM', 'MG.TL', 'MDG'],
                'MDV': ['MDV'],
                'MEX': ['MX.AG', 'MX.BS', 'MX.BN', 'MX.CM', 'MX.CP', 'MX.CH', 'MX.CA',
                        'MX.CL', 'MX.DF', 'MX.DU', 'MX.GJ', 'MX.GR', 'MX.HI', 'MX.JA',
                        'MX.MX', 'MX.MC', 'MX.MR', 'MX.NA', 'MX.NL', 'MX.OA', 'MX.PU',
                        'MX.QE', 'MX.QR', 'MX.SL', 'MX.SI', 'MX.SO', 'MX.TB', 'MX.TM',
                        'MX.TL', 'MX.VE', 'MX.YU', 'MX.ZA', 'MEX'], 'MHL': ['MHL'],
                'MKD': ['MK.AD', 'MK.AR', 'MK.BR', 'MK.TL', 'MK.BG', 'MK.VJ', 'MK.BS',
                        'MK.BN', 'MK.BU', 'MK.CI', 'MK.CA', 'MK.CE', 'MK.CZ', 'MK.CH',
                        'MK.CS', 'MK.DB', 'MK.DA', 'MK.DL', 'MK.DM', 'MK.DK', 'MK.DE',
                        'MK.DR', 'MK.GB', 'MK.GV', 'MK.GP', 'MK.GT', 'MK.GR', 'MK.IL',
                        'MK.JG', 'MK.KB', 'MK.KX', 'MK.AV', 'MK.KH', 'MK.VD', 'MK.OC',
                        'MK.KN', 'MK.KY', 'MK.KZ', 'MK.KG', 'MK.KS', 'MK.UM', 'MK.LI',
                        'MK.LO', 'MK.MK', 'MK.MD', 'MK.MR', 'MK.MG', 'MK.NG', 'MK.NV',
                        'MK.NS', 'MK.OD', 'MK.OS', 'MK.PH', 'MK.PE', 'MK.PN', 'MK.PP',
                        'MK.PT', 'MK.RV', 'MK.RN', 'MK.RE', 'MK.RM', 'MK.AJ', 'MK.SS',
                        'MK.SD', 'MK.NA', 'MK.ST', 'MK.UG', 'MK.RU', 'MK.SU', 'MK.SO',
                        'MK.SL', 'MK.TR', 'MK.ET', 'MK.VA', 'MK.VL', 'MK.VE', 'MK.VV',
                        'MK.NI', 'MK.VC', 'MK.VH', 'MK.ZA', 'MK.ZK', 'MK.ZE', 'MK.ZR',
                        'MKD'],
                'MLI': ['ML.BA', 'ML.GA', 'ML.KY', 'ML.KD', 'ML.KK', 'ML.MO', 'ML.SG',
                        'ML.SK', 'ML.TB', 'MLI'], 'MLT': ['MLT'],
                'MMR': ['MM.AY', 'MM.BA', 'MM.CH', 'MM.KC', 'MM.KH', 'MM.KN', 'MM.MG',
                        'MM.MD', 'MM.MO', 'MM.NY', 'MM.RA', 'MM.SA', 'MM.SH', 'MM.TN',
                        'MM.YA', 'MMR'],
                'MNE': ['ME.SA', 'ME.ZA', 'ME.AN', 'ME.BA', 'ME.BE', 'ME.BP', 'ME.BU',
                        'ME.CE', 'ME.DA', 'ME.HN', 'ME.KL', 'ME.KT', 'ME.MK', 'ME.NK',
                        'ME.PV', 'ME.PL', 'ME.PU', 'ME.PG', 'ME.RO', 'ME.TI', 'ME.UL',
                        'MNE'],
                'MNG': ['MN.OG', 'MN.OH', 'MN.AR', 'MN.BO', 'MN.BH', 'MN.BU', 'MN.DA',
                        'MN.DD', 'MN.DG', 'MN.DU', 'MN.DZ', 'MN.GA', 'MN.GS', 'MN.HG',
                        'MN.HN', 'MN.HD', 'MN.ER', 'MN.SB', 'MN.SL', 'MN.TO', 'MN.UB',
                        'MN.UV', 'MNG'],
                'MNP': ['MP.NI', 'MP.RO', 'MP.SA', 'MP.TI', 'MNP'],
                'MOZ': ['MZ.CD', 'MZ.GA', 'MZ.IN', 'MZ.MN', 'MZ.MC', 'MZ.MP', 'MZ.NM',
                        'MZ.NS', 'MZ.SO', 'MZ.TE', 'MZ.ZA', 'MOZ'],
                'MRT': ['MR.AD', 'MR.AS', 'MR.BR', 'MR.DN', 'MR.GO', 'MR.GD', 'MR.HC',
                        'MR.HG', 'MR.IN', 'MR.NO', 'MR.TG', 'MR.TZ', 'MR.TR', 'MRT'],
                'MSR': ['MS.SA', 'MS.SG', 'MS.SP', 'MSR'],
                'MUS': ['MU.AG', 'MU.BL', 'MU.FL', 'MU.GP', 'MU.MO', 'MU.PA', 'MU.PW',
                        'MU.PL', 'MU.RR', 'MU.RO', 'MU.CC', 'MU.SA', 'MUS'],
                'MWI': ['MW.BA', 'MW.BL', 'MW.CK', 'MW.CR', 'MW.CT', 'MW.DE', 'MW.DO',
                        'MW.KR', 'MW.KS', 'MW.LK', 'MW.LI', 'MW.MA', 'MW.MG', 'MW.MC',
                        'MW.MJ', 'MW.MN', 'MW.MZ', 'MW.NN', 'MW.NA', 'MW.NK', 'MW.NS',
                        'MW.NU', 'MW.NI', 'MW.PH', 'MW.RU', 'MW.SA', 'MW.TH', 'MW.ZO',
                        'MWI'],
                'MYS': ['MY.JH', 'MY.KH', 'MY.KN', 'MY.KL', 'MY.LA', 'MY.ME', 'MY.NS',
                        'MY.PH', 'MY.PK', 'MY.PL', 'MY.PG', 'MY.PJ', 'MY.SA', 'MY.SK',
                        'MY.SL', 'MY.TE', 'MYS'],
                'NAM': ['NA.KA', 'NA.ER', 'NA.HA', 'NA.OK', 'NA.KH', 'NA.KU', 'NA.OW',
                        'NA.OH', 'NA.OS', 'NA.ON', 'NA.OT', 'NA.OD', 'NA.CA', 'NAM'],
                'NCL': ['NC.IL', 'NC.NO', 'NC.SU', 'NCL'],
                'NER': ['NE.AG', 'NE.DF', 'NE.DS', 'NE.MA', 'NE.NI', 'NE.TH', 'NE.TL',
                        'NE.ZI', 'NER'], 'NFK': ['NFK'],
                'NGA': ['NG.AB', 'NG.AD', 'NG.AK', 'NG.AN', 'NG.BA', 'NG.BY', 'NG.BE',
                        'NG.BO', 'NG.CR', 'NG.DE', 'NG.EB', 'NG.ED', 'NG.EK', 'NG.EN',
                        'NG.FC', 'NG.GO', 'NG.IM', 'NG.JI', 'NG.KD', 'NG.KN', 'NG.KT',
                        'NG.KE', 'NG.KO', 'NG.KW', 'NG.LA', 'NG.NA', 'NG.NI', 'NG.OG',
                        'NG.ON', 'NG.OS', 'NG.OY', 'NG.PL', 'NG.RI', 'NG.SO', 'NG.TA',
                        'NG.YO', 'NG.ZA', 'NGA'],
                'NIC': ['NI.AN', 'NI.AS', 'NI.BO', 'NI.CA', 'NI.CI', 'NI.CO', 'NI.ES',
                        'NI.GR', 'NI.JI', 'lake', 'NI.LE', 'NI.MD', 'NI.MN', 'NI.MS',
                        'NI.MT', 'NI.NS', 'NI.SJ', 'NI.RI', 'NIC'], 'NIU': ['NIU'],
                'NLD': ['NL.DR', 'NL.FL', 'NL.FR', 'NL.GE', 'NL.GR', 'NL.LI', 'NL.NB',
                        'NL.NH', 'NL.OV', 'NL.UT', 'NL.ZE', 'NL.ZH', 'NLD'],
                'NOR': ['NO.OF', 'NO.AK', 'NO.AA', 'NO.BU', 'NO.FI', 'NO.HE', 'NO.HO',
                        'NO.MR', 'NO.NT', 'NO.NO', 'NO.OP', 'NO.OS', 'NO.RO', 'NO.ST',
                        'NO.SF', 'NO.TE', 'NO.TR', 'NO.VA', 'NO.VF', 'NOR'],
                'NPL': ['NP.MM', 'NP.PW', 'NP.SP', 'NP.MP', 'NP.PM', 'NPL'],
                'NRU': ['NR.AI', 'NR.AB', 'NR.AT', 'NR.AR', 'NR.BA', 'NR.BO', 'NR.BU',
                        'NR.DE', 'NR.EW', 'NR.IJ', 'NR.ME', 'NR.NI', 'NR.UA', 'NR.YA',
                        'NRU'],
                'NZL': ['NZ.AU', 'NZ.BP', 'NZ.CA', 'NZ.CI', 'NZ.GI', 'NZ.HB', 'NZ.MW',
                        'NZ.MA', 'NZ.NE', 'NZ.NO', 'NZ.OT', 'NZ.SO', 'NZ.TK', 'NZ.WK',
                        'NZ.WG', 'NZ.WC', 'NZL'],
                'OMN': ['OM.DA', 'OM.BN', 'OM.BS', 'OM.DH', 'OM.ZA', 'OM.WU', 'OM.SN',
                        'OM.SS', 'OM.JA', 'OM.MU', 'OM.MA', 'OMN'],
                'PAK': ['PK.JK', 'PK.BA', 'PK.TA', 'PK.IS', 'PK.NW', 'PK.NA', 'PK.PB',
                        'PK.SD', 'PAK'],
                'PAN': ['PA.BC', 'PA.CH', 'PA.CC', 'PA.CL', 'PA.DR', 'PA.EM', 'PA.HE',
                        'PA.SB', 'PA.LS', 'PA.NB', 'PA.PO', 'PA.PN', 'PA.VR', 'PAN'],
                'PCN': ['PCN'],
                'PER': ['PE.AM', 'PE.AN', 'PE.AP', 'PE.AR', 'PE.AY', 'PE.CJ', 'PE.CL',
                        'PE.CS', 'PE.HC', 'PE.HV', 'PE.IC', 'PE.JU', 'PE.LL', 'PE.LB',
                        'PE.LP', 'PE.LR', 'PE.LO', 'PE.MD', 'PE.MQ', 'PE.PA', 'PE.PI',
                        'PE.PU', 'PE.SM', 'PE.TA', 'PE.TU', 'PE.UC', 'PER'],
                'PHL': ['PH.AB', 'PH.AN', 'PH.AS', 'PH.AK', 'PH.AL', 'PH.AQ', 'PH.AP',
                        'PH.AU', 'PH.BS', 'PH.BA', 'PH.BN', 'PH.BT', 'PH.BG', 'PH.BI',
                        'PH.BO', 'PH.BK', 'PH.BU', 'PH.CG', 'PH.CN', 'PH.CS', 'PH.CM',
                        'PH.CP', 'PH.CT', 'PH.CV', 'PH.CB', 'PH.CL', 'PH.DV', 'PH.DS',
                        'PH.DO', 'PH.DI', 'PH.ES', 'PH.GU', 'PH.IF', 'PH.IN', 'PH.IS',
                        'PH.II', 'PH.IB', 'PH.KA', 'PH.LU', 'PH.LG', 'PH.LN', 'PH.LS',
                        'PH.LE', 'PH.MG', 'PH.MQ', 'PH.MB', 'PH.MM', 'PH.MD', 'PH.MN',
                        'PH.MT', 'PH.ND', 'PH.NR', 'PH.NC', 'PH.NS', 'PH.NE', 'PH.NV',
                        'PH.MC', 'PH.MR', 'PH.PL', 'PH.PM', 'PH.PN', 'PH.QZ', 'PH.QR',
                        'PH.RI', 'PH.RO', 'PH.SM', 'PH.SG', 'PH.SQ', 'PH.SR', 'PH.SC',
                        'PH.SL', 'PH.SK', 'PH.SU', 'PH.SN', 'PH.SS', 'PH.TR', 'PH.TT',
                        'PH.ZN', 'PH.ZS', 'PH.ZY', 'PHL'],
                'PLW': ['PW.AM', 'PW.AR', 'PW.PE', 'PW.HA', 'PW.KA', 'PW.KO', 'PW.ME',
                        'PW.ND', 'PW.NC', 'PW.NM', 'PW.NP', 'PW.NS', 'PW.NL', 'PW.NW',
                        'PW.SO', 'PLW'],
                'PNG': ['PG.NS', 'PG.CE', 'PG.CH', 'PG.EN', 'PG.ES', 'PG.EH', 'PG.EG',
                        'PG.GU', 'PG.HE', 'PG.JI', 'PG.MD', 'PG.MN', 'PG.MB', 'PG.MR',
                        'PG.NC', 'PG.NI', 'PG.NO', 'PG.SA', 'PG.SL', 'PG.WN', 'PG.WH',
                        'PG.WL', 'PG.WE', 'PNG'],
                'POL': ['PL.LD', 'PL.SK', 'PL.WP', 'PL.KP', 'PL.MA', 'PL.DS', 'PL.LU',
                        'PL.LB', 'PL.MZ', 'PL.OP', 'PL.PD', 'PL.PM', 'PL.SL', 'PL.PK',
                        'PL.WN', 'PL.ZP', 'POL'],
                'PRI': ['PR.AN', 'PR.AJ', 'PR.AD', 'PR.AL', 'PR.AB', 'PR.AI', 'PR.AC',
                        'PR.AR', 'PR.BC', 'PR.BQ', 'PR.BY', 'PR.CR', 'PR.CG', 'PR.CA',
                        'PR.CV', 'PR.CN', 'PR.CT', 'PR.CY', 'PR.CB', 'PR.CL', 'PR.CD',
                        'PR.CO', 'PR.CM', 'PR.CZ', 'PR.CU', 'PR.DO', 'PR.FJ', 'PR.FL',
                        'PR.GC', 'PR.GM', 'PR.GL', 'PR.GB', 'PR.GR', 'PR.HA', 'PR.HO',
                        'PR.HU', 'PR.IS', 'PR.JY', 'PR.JD', 'PR.JC', 'PR.LJ', 'PR.LR',
                        'PR.LM', 'PR.LP', 'PR.LZ', 'PR.LQ', 'PR.MT', 'PR.MR', 'PR.MB',
                        'PR.MG', 'PR.MC', 'PR.MV', 'PR.NG', 'PR.NR', 'PR.OR', 'PR.PT',
                        'PR.PN', 'PR.PO', 'PR.QB', 'PR.RG', 'PR.RC', 'PR.SB', 'PR.SA',
                        'PR.SG', 'PR.SJ', 'PR.SL', 'PR.SS', 'PR.SI', 'PR.TA', 'PR.TB',
                        'PR.TJ', 'PR.UT', 'PR.VA', 'PR.VB', 'PR.VQ', 'PR.VL', 'PR.YB',
                        'PR.YU', 'PRI'],
                'PRK': ['KP.CH', 'KP.HG', 'KP.HN', 'KP.WB', 'KP.WN', 'KP.KS', 'KP.KW',
                        'KP.PB', 'KP.PN', 'KP.PY', 'KP.NJ', 'KP.YG', 'PRK'],
                'PRT': ['PT.AV', 'PT.AC', 'PT.BE', 'PT.BR', 'PT.BA', 'PT.CB', 'PT.CO',
                        'PT.EV', 'PT.FA', 'PT.GU', 'PT.LE', 'PT.LI', 'PT.PA', 'PT.PO',
                        'PT.SA', 'PT.SE', 'PT.VC', 'PT.VR', 'PT.VI', 'PRT'],
                'PRY': ['PY.NE', 'PY.AG', 'PY.AA', 'PY.AM', 'PY.AS', 'PY.BQ', 'PY.CG',
                        'PY.CZ', 'PY.CY', 'PY.CE', 'PY.CN', 'PY.CR', 'PY.GU', 'PY.IT',
                        'PY.MI', 'PY.PG', 'PY.PH', 'PY.SP', 'PRY'],
                'PSE': ['PSE', 'PSE.1_1', 'PSE.2_1'],
                'PYF': ['PF.TI', 'PF.WI', 'PF.MI', 'PF.LI', 'PF.TG', 'PYF'],
                'QAT': ['QA.DA', 'QA.DY', 'QA.KR', 'QA.WA', 'QA.RY', 'QA.MS', 'QA.SL',
                        'QAT'],
                'ROU': ['RO.AB', 'RO.AR', 'RO.AG', 'RO.BC', 'RO.BH', 'RO.BN', 'RO.BT',
                        'RO.BV', 'RO.BR', 'RO.BI', 'RO.BZ', 'RO.CL', 'RO.CS', 'RO.CJ',
                        'RO.CT', 'RO.CV', 'RO.DB', 'RO.DJ', 'RO.GL', 'RO.GR', 'RO.GJ',
                        'RO.HR', 'RO.HD', 'RO.IS', 'RO.IL', 'RO.IF', 'RO.MM', 'RO.MH',
                        'RO.MS', 'RO.NT', 'RO.OT', 'RO.PH', 'RO.SJ', 'RO.SM', 'RO.SB',
                        'RO.SV', 'RO.TR', 'RO.TM', 'RO.TL', 'RO.VL', 'RO.VS', 'RO.VN',
                        'ROU'],
                'RUS': ['RU.AD', 'RU.AL', 'RU.AM', 'RU.AR', 'RU.AS', 'RU.BK', 'RU.BL',
                        'RU.BR', 'RU.BU', 'RU.CN', 'RU.CL', 'RU.CK', 'RU.CV', 'RU.SP',
                        'RU.DA', 'RU.GA', 'RU.IN', 'RU.IK', 'RU.IV', 'RU.KB', 'RU.KN',
                        'RU.KL', 'RU.KG', 'RU.KQ', 'RU.KC', 'RU.KI', 'RU.KE', 'RU.KH',
                        'RU.KK', 'RU.KM', 'RU.KV', 'RU.KO', 'RU.KT', 'RU.KD', 'RU.KX',
                        'RU.KU', 'RU.KS', 'RU.LN', 'RU.LP', 'RU.MG', 'RU.ME', 'RU.MR',
                        'RU.MS', 'RU.MM', 'RU.NN', 'RU.NZ', 'RU.NO', 'RU.NG', 'RU.NS',
                        'RU.OM', 'RU.OL', 'RU.OB', 'RU.PZ', 'RU.PE', 'RU.PR', 'RU.PS',
                        'RU.RO', 'RU.RZ', 'RU.SK', 'RU.SL', 'RU.SA', 'RU.SR', 'RU.SM',
                        'RU.ST', 'RU.SV', 'RU.TB', 'RU.TT', 'RU.TO', 'RU.TL', 'RU.TU',
                        'RU.TV', 'RU.TY', 'RU.UD', 'RU.UL', 'RU.VL', 'RU.VG', 'RU.VO',
                        'RU.VR', 'RU.YN', 'RU.YS', 'RU.YV', 'RU.ZB', 'RUS'],
                'RWA': ['RW.NO', 'RW.SU', 'RW.ES', 'RW.OU', 'RW.KV', 'RWA'],
                'SAU': ['SA.AS', 'SA.BA', 'SA.HS', 'SA.JF', 'SA.MD', 'SA.QS', 'SA.RI',
                        'SA.SH', 'SA.HA', 'SA.JZ', 'SA.MK', 'SA.NJ', 'SA.TB', 'SAU'],
                'SDN': ['SD.GZ', 'SD.GD', 'SD.BN', 'SD.CD', 'SD.ED', 'SD.KA', 'SD.KH',
                        'SD.ND', 'SD.KN', 'SD.NO', 'SD.RS', 'SD.RN', 'SD.SI', 'SD.SD',
                        'SD.KS', 'SD.WD', 'SD.WN', 'SDN'],
                'SEN': ['SN.DK', 'SN.DB', 'SN.FK', 'SN.KG', 'SN.KF', 'SN.KC', 'SN.KD',
                        'SN.LG', 'SN.MT', 'SN.SD', 'SN.ST', 'SN.TB', 'SN.TH', 'SN.ZG',
                        'SEN'], 'SGP': ['SGP'], 'SGS': ['SGS'],
                'SHN': ['SH.AC', 'SH.SH', 'SH.TA', 'SHN'],
                'SLB': ['SB.CN', 'SB.CH', 'SB.GU', 'SB.CT', 'SB.IS', 'SB.MK', 'SB.ML',
                        'SB.RB', 'SB.TE', 'SB.WE', 'SLB'],
                'SLE': ['SL.EA', 'SL.NO', 'SL.SO', 'SL.WE', 'SLE'],
                'SLV': ['SV.AH', 'SV.CA', 'SV.CH', 'SV.CU', 'SV.LI', 'SV.PA', 'SV.UN',
                        'SV.MO', 'SV.SM', 'SV.SS', 'SV.SV', 'SV.SA', 'SV.SO', 'SV.US',
                        'SLV'],
                'SMR': ['SM.AC', 'SM.BM', 'SM.CH', 'SM.DO', 'SM.FA', 'SM.FI', 'SM.MG',
                        'SM.SM', 'SM.SE', 'SMR'],
                'SOM': ['SO.AW', 'SO.BK', 'SO.BN', 'SO.BR', 'SO.BY', 'SO.GA', 'SO.GE',
                        'SO.HI', 'SO.JD', 'SO.JH', 'SO.MU', 'SO.NU', 'SO.SA', 'SO.SD',
                        'SO.SH', 'SO.SO', 'SO.TO', 'SO.WO', 'SOM'],
                'SPM': ['PM.ML', 'PM.SP', 'SPM'],
                'SRB': ['RS.SU', 'RS.BO', 'RS.BR', 'RS.BG', 'RS.JA', 'RS.JC', 'RS.JN',
                        'RS.KB', 'RS.MA', 'RS.MR', 'RS.NS', 'RS.PC', 'RS.PI', 'RS.PD',
                        'RS.PM', 'RS.RS', 'RS.RN', 'RS.SC', 'RS.SN', 'RS.SD', 'RS.SM',
                        'RS.TO', 'RS.ZJ', 'RS.ZC', 'RS.ZL', 'SRB'],
                'SSD': ['SSD', 'SSD.1_1', 'SSD.2_1', 'SSD.3_1', 'SSD.4_1', 'SSD.5_1',
                        'SSD.6_1', 'SSD.7_1', 'SSD.8_1', 'SSD.9_1', 'SSD.10_1'],
                'STP': ['ST.PR', 'ST.ST', 'STP'],
                'SUR': ['SR.BR', 'SR.CM', 'SR.CR', 'SR.MA', 'SR.NI', 'SR.PR', 'SR.PM',
                        'SR.SA', 'SR.SI', 'SR.WA', 'SUR'],
                'SVK': ['SK.ZI', 'SK.BC', 'SK.BL', 'SK.KI', 'SK.NI', 'SK.PV', 'SK.TC',
                        'SK.TA', 'SVK'],
                'SVN': ['SI.GO', 'SI.SP', 'SI.KO', 'SI.NO', 'SI.JP', 'SI.LJ', 'SI.PD',
                        'SI.PM', 'SI.SA', 'SI.PS', 'SI.ZS', 'SVN'],
                'SWE': ['SE.OG', 'SE.BL', 'SE.KO', 'SE.GV', 'SE.GT', 'SE.HA', 'SE.JA',
                        'SE.JO', 'SE.KA', 'SE.KR', 'SE.NB', 'SE.OR', 'SE.SD', 'SE.SN',
                        'SE.ST', 'SE.UP', 'SE.VR', 'SE.VB', 'SE.VN', 'SE.VM', 'SE.VG',
                        'SWE'], 'SWZ': ['SZ.HH', 'SZ.LU', 'SZ.MA', 'SZ.SH', 'SWZ'],
                'SXM': ['SXM'],
                'SYC': ['SC.ET', 'SC.PI', 'SC.AB', 'SC.RO', 'SC.LO', 'SC.BL', 'SC.BS',
                        'SC.BV', 'SC.BA', 'SC.BO', 'SC.CA', 'SC.RA', 'SC.GL', 'SC.GM',
                        'SC.GP', 'SC.DI', 'SC.LM', 'SC.MB', 'SC.MF', 'SC.OI', 'SC.PL',
                        'SC.PR', 'SC.PG', 'SC.RC', 'SC.SL', 'SC.TA', 'SYC'],
                'SYR': ['SY.HA', 'SY.HL', 'SY.RA', 'SY.SU', 'SY.DI', 'SY.DR', 'SY.DY',
                        'SY.HM', 'SY.HI', 'SY.ID', 'SY.LA', 'SY.QU', 'SY.RD', 'SY.TA',
                        'SYR'], 'TCA': ['TCA'],
                'TCD': ['TD.BG', 'TD.BA', 'TD.BR', 'TD.CB', 'TD.EE', 'TD.EO', 'TD.GR',
                        'TD.HD', 'TD.KM', 'TD.LC', 'TD.LO', 'TD.LR', 'TD.MA', 'TD.ME',
                        'TD.MW', 'TD.MC', 'TD.OA', 'TD.SA', 'TD.SI', 'TD.TA', 'TD.TI',
                        'TD.NJ', 'TD.BI', 'TCD'],
                'TGO': ['TG.CE', 'TG.KA', 'TG.MA', 'TG.PL', 'TG.SA', 'TGO'],
                'THA': ['TH.AC', 'TH.AT', 'TH.BM', 'TH.BK', 'TH.BR', 'TH.CC', 'TH.CN',
                        'TH.CY', 'TH.CT', 'TH.CM', 'TH.CR', 'TH.CB', 'TH.CP', 'TH.KL',
                        'TH.KP', 'TH.KN', 'TH.KK', 'TH.KR', 'TH.LG', 'TH.LN', 'TH.LE',
                        'TH.LB', 'TH.MH', 'TH.MS', 'TH.MD', 'TH.NN', 'TH.NP', 'TH.NF',
                        'TH.NR', 'TH.NS', 'TH.NT', 'TH.NA', 'TH.NW', 'TH.NB', 'TH.NK',
                        'TH.NO', 'TH.PT', 'TH.PI', 'TH.PG', 'TH.PL', 'TH.PY', 'TH.PH',
                        'TH.PE', 'TH.PC', 'TH.PS', 'TH.PA', 'TH.PR', 'TH.PU', 'TH.PB',
                        'TH.PK', 'TH.RN', 'TH.RT', 'TH.RY', 'TH.RE', 'TH.SK', 'TH.SN',
                        'TH.SP', 'TH.SS', 'TH.SM', 'TH.SR', 'TH.SA', 'TH.SI', 'TH.SB',
                        'TH.SG', 'TH.SO', 'TH.SH', 'TH.ST', 'TH.SU', 'TH.TK', 'TH.TG',
                        'TH.TT', 'TH.UR', 'TH.UN', 'TH.UT', 'TH.UD', 'TH.YL', 'TH.YS',
                        'THA'], 'TJK': ['TJ.RR', 'TJ.BK', 'TJ.KL', 'TJ.LE', 'TJK'],
                'TKM': ['TM.AB', 'TM.AL', 'TM.BA', 'TM.LE', 'TM.MA', 'TM.DA', 'TKM'],
                'TLS': ['TP.AL', 'TP.AN', 'TP.AM', 'TP.BC', 'TP.BB', 'TP.CL', 'TP.DL',
                        'TP.ER', 'TP.BT', 'TP.LQ', 'TP.MT', 'TP.MF', 'TP.VQ', 'TLS'],
                'TON': ['TO.EU', 'TO.HA', 'TO.NI', 'TO.TT', 'TO.VA', 'TON'],
                'TTO': ['TT.AR', 'TT.CH', 'TT.CT', 'TT.DM', 'TT.MR', 'TT.PD', 'TT.PF',
                        'TT.PS', 'TT.PT', 'TT.SF', 'TT.SL', 'TT.SN', 'TT.SI', 'TT.TB',
                        'TT.TP', 'TTO'],
                'TUN': ['TN.AN', 'TN.BJ', 'TN.BA', 'TN.BZ', 'TN.GB', 'TN.GF', 'TN.JE',
                        'TN.KR', 'TN.KS', 'TN.KB', 'TN.KF', 'TN.MH', 'TN.MN', 'TN.ME',
                        'TN.MS', 'TN.NB', 'TN.SF', 'TN.SZ', 'TN.SL', 'TN.SS', 'TN.TA',
                        'TN.TO', 'TN.TU', 'TN.ZA', 'TUN'],
                'TUR': ['TR.CK', 'TR.CI', 'TR.CM', 'TR.AA', 'TR.AD', 'TR.AF', 'TR.AG',
                        'TR.AK', 'TR.AM', 'TR.AN', 'TR.AL', 'TR.AR', 'TR.AV', 'TR.AY',
                        'TR.BK', 'TR.BR', 'TR.BM', 'TR.BB', 'TR.BC', 'TR.BG', 'TR.BT',
                        'TR.BL', 'TR.BD', 'TR.BU', 'TR.DU', 'TR.DN', 'TR.DY', 'TR.ED',
                        'TR.EG', 'TR.EN', 'TR.EM', 'TR.ES', 'TR.GU', 'TR.GA', 'TR.GI',
                        'TR.HK', 'TR.HT', 'TR.IG', 'TR.IP', 'TR.IB', 'TR.IZ', 'TR.KM',
                        'TR.KU', 'TR.KB', 'TR.KR', 'TR.KA', 'TR.KS', 'TR.KY', 'TR.KI',
                        'TR.KK', 'TR.KL', 'TR.KH', 'TR.KC', 'TR.KO', 'TR.ML', 'TR.MN',
                        'TR.MR', 'TR.IC', 'TR.MG', 'TR.MS', 'TR.NV', 'TR.NG', 'TR.OR',
                        'TR.OS', 'TR.RI', 'TR.SK', 'TR.SS', 'TR.SU', 'TR.SI', 'TR.SP',
                        'TR.SR', 'TR.SV', 'TR.TG', 'TR.TT', 'TR.TB', 'TR.TC', 'TR.US',
                        'TR.VA', 'TR.YL', 'TR.YZ', 'TR.ZO', 'TUR'],
                'TWN': ['TW.FK', 'TW.KH', 'TW.NT', 'TW.TG', 'TW.TN', 'TW.TP', 'TW.TA',
                        'TWN'],
                'TZA': ['TZ.AS', 'TZ.DS', 'TZ.DO', 'TZ.GE', 'TZ.IG', 'TZ.KG', 'TZ.KA',
                        'TZ.KM', 'TZ.KL', 'TZ.LI', 'TZ.MY', 'TZ.MA', 'TZ.MB', 'TZ.MO',
                        'TZ.MT', 'TZ.MZ', 'TZ.NJ', 'TZ.PN', 'TZ.PS', 'TZ.PW', 'TZ.RU',
                        'TZ.RV', 'TZ.SY', 'TZ.SI', 'TZ.SD', 'TZ.TB', 'TZ.TN', 'TZ.ZN',
                        'TZ.ZS', 'TZ.ZW', 'TZA'],
                'UGA': ['UG.AD', 'UG.AC', 'UG.AW', 'UG.BG', 'UG.BN', 'UG.BS', 'UG.BU',
                        'UG.GL', 'UG.HO', 'UG.IN', 'UG.JI', 'UG.KA', 'UG.BR', 'UG.KD',
                        'UG.KN', 'UG.KM', 'UG.KX', 'UG.KE', 'UG.UU', 'UG.KP', 'UG.KS',
                        'UG.KK', 'UG.KY', 'UG.KI', 'UG.KG', 'UG.KR', 'UG.TG', 'UG.KF',
                        'UG.KU', 'UG.KJ', 'UG.LA', 'UG.LW', 'UG.MA', 'UG.MC', 'UG.MG',
                        'UG.ME', 'UG.RR', 'UG.MT', 'UG.MY', 'UG.MI', 'UG.MD', 'UG.MN',
                        'UG.NP', 'UG.NA', 'UG.NE', 'UG.NT', 'UG.PD', 'UG.PL', 'UG.RA',
                        'UG.RK', 'UG.SE', 'UG.SI', 'UG.SR', 'UG.TR', 'UG.WA', 'UG.YU',
                        'UGA'],
                'UKR': ['UA.CK', 'UA.CH', 'UA.CV', 'UA.KR', 'UA.DP', 'UA.DT', 'UA.IF',
                        'UA.KK', 'UA.KS', 'UA.KM', 'UA.KC', 'UA.KV', 'UA.KH', 'UA.LV',
                        'UA.LH', 'UA.MY', 'UA.OD', 'UA.PL', 'UA.RV', 'UA.SC', 'UA.SM',
                        'UA.TP', 'UA.ZK', 'UA.VI', 'UA.VO', 'UA.ZP', 'UA.ZT', 'UKR'],
                'URY': ['UY.AR', 'UY.CA', 'UY.CL', 'UY.CO', 'UY.DU', 'UY.FS', 'UY.FD',
                        'UY.LA', 'UY.MA', 'UY.MO', 'UY.PA', 'UY.RN', 'UY.RV', 'UY.RO',
                        'UY.SA', 'UY.SJ', 'UY.SO', 'UY.TA', 'UY.TT', 'URY'],
                'USA': ['US.AL', 'US.AK', 'US.AZ', 'US.AR', 'US.CA', 'US.CO', 'US.CT',
                        'US.DE', 'US.DC', 'US.FL', 'US.GA', 'US.HI', 'US.ID', 'US.IL',
                        'US.IN', 'US.IA', 'US.KS', 'US.KY', 'US.LA', 'US.ME', 'US.MD',
                        'US.MA', 'US.MI', 'US.MN', 'US.MS', 'US.MO', 'US.MT', 'US.NE',
                        'US.NV', 'US.NH', 'US.NJ', 'US.NM', 'US.NY', 'US.NC', 'US.ND',
                        'US.OH', 'US.OK', 'US.OR', 'US.PA', 'US.RI', 'US.SC', 'US.SD',
                        'US.TN', 'US.TX', 'US.UT', 'US.VT', 'US.VA', 'US.WA', 'US.WV',
                        'US.WI', 'US.WY', 'USA'],
                'UZB': ['UZ.AN', 'UZ.BU', 'UZ.FA', 'UZ.JI', 'UZ.QR', 'UZ.QA', 'UZ.KH',
                        'UZ.NG', 'UZ.NW', 'UZ.SA', 'UZ.SI', 'UZ.SU', 'UZ.TK', 'UZ.TA',
                        'UZB'], 'VAT': ['VAT'],
                'VCT': ['VC.CH', 'VC.GT', 'VC.AN', 'VC.DA', 'VC.GE', 'VC.PA', 'VCT'],
                'VEN': ['VE.DP', 'VEN'], 'VGB': ['VGB'],
                'VIR': ['VI.SC', 'VI.SJ', 'VI.ST', 'VIR'],
                'VNM': ['VN.DA', 'VN.DN', 'VN.DT', 'VN.DO', 'VN.DC', 'VN.DB', 'VN.AG',
                        'VN.BV', 'VN.BD', 'VN.BI', 'VN.BP', 'VN.BU', 'VN.BL', 'VN.BG',
                        'VN.BK', 'VN.BN', 'VN.BR', 'VN.CM', 'VN.CB', 'VN.CN', 'VN.GL',
                        'VN.HG', 'VN.HN', 'VN.HM', 'VN.HT', 'VN.HC', 'VN.HO', 'VN.HY',
                        'VN.HD', 'VN.HP', 'VN.HU', 'VN.KH', 'VN.KG', 'VN.KT', 'VN.LO',
                        'VN.LD', 'VN.LI', 'VN.LS', 'VN.LA', 'VN.ND', 'VN.NA', 'VN.NB',
                        'VN.NT', 'VN.PT', 'VN.PY', 'VN.QB', 'VN.QM', 'VN.QG', 'VN.QN',
                        'VN.QT', 'VN.ST', 'VN.SL', 'VN.TN', 'VN.TB', 'VN.TY', 'VN.TT',
                        'VN.TH', 'VN.TG', 'VN.TV', 'VN.TQ', 'VN.VL', 'VN.VC', 'VN.YB',
                        'VNM'],
                'VUT': ['VU.ML', 'VU.PM', 'VU.SN', 'VU.SE', 'VU.TF', 'VU.TR', 'VUT'],
                'WLF': ['WF.AL', 'WF.SI', 'WF.UV', 'WLF'],
                'WSM': ['WS.AA', 'WS.AL', 'WS.AT', 'WS.FA', 'WS.GE', 'WS.GI', 'WS.PA',
                        'WS.SA', 'WS.TU', 'WS.VF', 'WS.VS', 'WSM'],
                'YEM': ['YE.AD', 'YE.AB', 'YE.BA', 'YE.DL', 'YE.HU', 'YE.JA', 'YE.MR',
                        'YE.MW', 'YE.AM', 'YE.DH', 'YE.HD', 'YE.HJ', 'YE.IB', 'YE.LA',
                        'YE.MA', 'YE.SD', 'YE.SN', 'YE.SH', 'YE.TA', 'YEM'],
                'ZAF': ['ZA.EC', 'ZA.FS', 'ZA.GT', 'ZA.NL', 'ZA.NP', 'ZA.MP', 'ZA.NW',
                        'ZA.NC', 'ZA.WC', 'ZAF'],
                'ZMB': ['ZM.CE', 'ZM.CO', 'ZM.EA', 'ZM.LP', 'ZM.LS', 'ZM.MU', 'ZM.NW',
                        'ZM.NO', 'ZM.SO', 'ZM.WE', 'ZMB'],
                'ZWE': ['ZW.BU', 'ZW.HA', 'ZW.MA', 'ZW.MC', 'ZW.ME', 'ZW.MW', 'ZW.MV',
                        'ZW.MN', 'ZW.MS', 'ZW.MI', 'ZWE']}
